account_id = "41c9566f8e5156586950ce7810dea816"
name = "personal_website"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-02-13"
